FROM python:3.12-slim

LABEL maintainer="Pilatuña López Luis Alexander"
LABEL description="Pipeline de Anonimización y Tokenización - TFMT"

WORKDIR /app

# Dependencias del sistema
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Dependencias Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Código del pipeline
COPY pipeline/ ./pipeline/
COPY config/   ./config/

# Crear directorio de logs
RUN mkdir -p /app/logs

CMD ["python", "-m", "pipeline.orchestrator"]
